version: "2.3"

networks:
  default:
    external:
      name: net_substra

services:
  substra_frontend:
    build:
      context: ./
    container_name: substra-frontend
    hostname: substra-frontend
    depends_on:
      - redis
    ports:
      - "3000:8000"
    restart: unless-stopped
    environment:
      - API_URL=$API_URL
      - BACK_AUTH_USER=$BACK_AUTH_USER
      - BACK_AUTH_PASSWORD=$BACK_AUTH_PASSWORD
      - FRONT_AUTH_USER=$FRONT_AUTH_USER
      - FRONT_AUTH_PASSWORD=$FRONT_AUTH_PASSWORD
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - NODE_PORT=$NODE_PORT
      - SECURE_NODE_PORT=$SECURE_NODE_PORT
  redis:
    container_name: redis
    hostname: redis
    image: redis:4.0.11-alpine
    restart: unless-stopped
